### ISSUE TITLE
some ddl callback clauses are duplicated

### ISSUE THREAD

**Issue by ruslandoga** [elixir-sqlite/ecto_sqlite3#102]
These two ranges seem to be duplicated. The second one seems "more complete", it has exceptions on constraints and uses prefix in table renaming. Except, what are table prefixes in SQLite?

https://github.com/elixir-sqlite/ecto_sqlite3/blob/6dcc0b2410ac2e2727d6c81ecb2e96c410eb8be4/lib/ecto/adapters/sqlite3/connection.ex#L460-L562

and

https://github.com/elixir-sqlite/ecto_sqlite3/blob/6dcc0b2410ac2e2727d6c81ecb2e96c410eb8be4/lib/ecto/adapters/sqlite3/connection.ex#L564-L685

**Comment by warmwaffles** [comment]
Oh that's weird. I wonder why it wasn't caught by linting or the compiler?

**Comment by ruslandoga** [comment]
I wondered that too, so I had to double check the clauses are in fact the same. Maybe `@impl true` has something to do with it? Or maybe the expressions in the clauses are "too complex".

**Comment by warmwaffles** [comment]
It very well could be all the `@impl true`s. I think we should remove them to be set on the first defined method of the implementation.

**Comment by warmwaffles** [comment]
@ruslandoga table prefixes IIRC is a way to prefix table names via a config. https://hexdocs.pm/ecto_sql/Ecto.Migration.html#module-prefixes

We definitely need to support the table prefixing.

**Comment by ruslandoga** [comment]
But does sqlite support them?

```sql
sqlite> create table prefix.table(a integer);
Parse error: near "table": syntax error
  create table prefix.table(a integer);
                      ^--- error here
```

**Comment by warmwaffles** [comment]
It does not, but we can support it via `<prefix>_<tablename>`

**Comment by warmwaffles** [comment]
Or we could just throw our hands up in the air and raise an exception saying that is is not supported.

**Comment by warmwaffles** [comment]
I'm okay with removing the prefix support and failing loudly. We'd need to make clear call out in the changelog that it is a breaking change and will need to be accounted for.

**Comment by ruslandoga** [comment]
If it's ok with you, I'd like to try and work on this tomorrow :)

**Comment by warmwaffles** [comment]
I'm all good with that.

I took a stab at adding dialyzer here too to see if it would catch the duplicate function definition. But that was a mess to deal with.
