### ISSUE TITLE
fragments in select

### ISSUE THREAD

**Issue by ruslandoga** [elixir-sqlite/ecto_sqlite3#104]
This query doesn't seem to work with SQLite3 https://github.com/elixir-sqlite/ecto_sqlite3/blob/6dcc0b2410ac2e2727d6c81ecb2e96c410eb8be4/test/ecto/adapters/sqlite3/connection_test.exs#L139-L144

```sql
sqlite> create table example(a integer);

sqlite> select e0 from "example" as e0;
Parse error: no such column: e0
  select e0 from "example" as e0;
         ^--- error here
```

I wonder if there is something we can do about it. Either raise or add `.*`.

**Comment by ruslandoga** [comment]
Postgrex has a similar test case

https://github.com/elixir-ecto/ecto_sql/blob/c7d58a3f963cc605ef73c4eec2c03fc46c6db804/test/ecto/adapters/postgres_test.exs#L87-L88

I'll check if that query works with postgres and if not, I'll reopen this issue on ecto_sql.

**Comment by warmwaffles** [comment]
Oh that's confusing. We should do what is right and just raise here honestly. Doing a naked select like that and appending `.*` seems risky to me. Thoughts?
