### ISSUE TITLE
EctoSQLite3.MixProject.project/0 is undefined (module EctoSQLite3.MixProject is not available)

### ISSUE THREAD

**Issue by gazzer82** [elixir-sqlite/ecto_sqlite3#109]
I am trying to use EctoSQLite3 in a phoenix project:

```
      {:phoenix, "~> 1.7.1"},
      {:phoenix_ecto, "~> 4.4"},
      {:ecto_sql, "~> 3.6"},
      {:postgrex, ">= 0.0.0"},
```

I am getting the following error from ElixirLS

`EctoSQLite3.MixProject.project/0 is undefined (module EctoSQLite3.MixProject is not available)`

This seems to happen with a completely vanilla Phoenix project created with:

`mix phx.new test --database sqlite3`

The biggest variable here, is I am on an m1 MacBook Pro, so exqlite is being compile to `aarch64-apple-darwin` rather that using a precompiled binary, maybe?

Everything does seem to be working as expected, but my ocd needs to clear the error . . . 

Thanks!

**Comment by warmwaffles** [comment]
Hmm, this seems like an upstream generator issue with phoenix.

You need to swap out `postgrex` with `ecto_sqlite3` which will then bring the project in and it will find that `MixProject` module.

**Comment by warmwaffles** [comment]
@gazzer82 are you able to push the project up to github so I can check it out and help?

**Comment by joeljuca** [comment]
I just ran some more tests. Projects created with a recent version of `phx.new` seem to be configured appropriately and work fine. This might be an issue with an outdated Phoenix generator (most probably), or some issue with Elixir versions (least probably).
