### ISSUE TITLE
Better defaults

### ISSUE THREAD

**Issue by kevinlang** [elixir-sqlite/ecto_sqlite3#11]
Right now `Exqlite` has some "opinionated" recommendations like defaulting FK to `on`, but defers to the application developer to configure things like `journal_mode`. I think that, at least in the Ecto adapter, that opinionated approach should be extended to the other options, like `journal_mode`. This is from my experience reading forums and issues around SQLite where novice developers do not understand that they need to set `busy_timeout` and `journal_mode` to a better defualt value. This is also reflected in the sentiment in the SQLite forums and maintainers where these options are lauded and only not turned on because of backwards compatability concerns.

What do you think @warmwaffles ?

If so, the question is whether these more sane defaults should be shared across both Exqlite and this adapter. I can see the appeal of the Exqlite adapter being more conservative and less prescriptive, as those who need to use the driver directly probably know what they are doing and would expect the defaults to be nearer the SQLite defaults.

**Comment by warmwaffles** [comment]
I think it would be okay to set the defaults to 

```
  journal_mode: :wal,
  cache_size: -64000,
  temp_store: :memory,
  pool_size: 5,
```

As a good starting point. That's what I've been using in my personal projects and it seems to hold well. Probably need more extensive documentation and links to discussions around the configuration recommendations. 

I just set the defaults that sqlite3 has by default.
