### ISSUE TITLE
But how do I use this with ecto.create?

### ISSUE THREAD

**Issue by jdmarshall** [elixir-sqlite/ecto_sqlite3#114]
There are no instructions I can find for beginners to get from mix phx.new to a working phoenix project.

There seems to be a circular dependency in the documentation.

I'm unclear why you should need to do any manual steps to get phx.new working. Why is that dependency not already set up?

**Comment by jdmarshall** [comment]
` could not compile dependency :exqlite, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile exqlite", update it with "mix deps.update exqlite" or clean it with "mix deps.clean exqlite"
`

**Comment by joeljuca** [comment]
@warmwaffles This issue has been hanging for quite some time, without much attention from the reporter itself. I think it can be closed already.

**Comment by warmwaffles** [comment]
Agreed
