### ISSUE TITLE
Does ecto_sqlite3 supports the query prefixes?

### ISSUE THREAD

**Issue by joeljuca** [elixir-sqlite/ecto_sqlite3#118]
I'm wondering if ecto_sqlite3 supports [query prefixes](https://hexdocs.pm/ecto/Ecto.Query.html#module-query-prefix) in the Query/Schema API. I'm considering using multiple SQLite databases instead of a bigger one (one for each client) and the query prefixes could be very helpful in this scenario.

If it doesn't support today, what do you think it would take to implement the feature? I'm not that familiar with the codebase just yet, hence the question.

**Comment by warmwaffles** [comment]
It _should_ support query prefixes. But they do not function like they do in the postgres adapter which I believe shifts to a different schema.

**Comment by joeljuca** [comment]
Yeah, I wonder how query prefixes would work: would they query another table, based on the prefix - or would it query another SQLite database?

**Comment by warmwaffles** [comment]
@joeljuca it would just prefix the table names unfortunately. SQLite does not have any notion of schemas. It's all just one schema. Not ideal, but also not a huge deal.

As for using multiple databases, check out https://hexdocs.pm/ecto/replicas-and-dynamic-repositories.html

**Comment by joeljuca** [comment]
Awesome! Thank you, @warmwaffles!

**Comment by warmwaffles** [comment]
I've had good success with dynamic repos, but they are quirky, and running migrations across all of them is a release task that you need to program for. Not the end of the world.
