### ISSUE TITLE
Don't need to pattern match on `{:maybe, type}` in upcoming Ecto release

### ISSUE THREAD

**Issue by greg-rychlewski** [elixir-sqlite/ecto_sqlite3#120]
With the given change https://github.com/elixir-ecto/ecto/pull/4265 you don't have to pattern match on `{:maybe, type}` anymore. I don't think it will hurt if you leave it as is but just wanted to give you a heads up.

**Comment by warmwaffles** [comment]
Thanks for the heads up. I'll keep this open to remind me to go yank once that lands.
