### ISSUE TITLE
ETA on next release

### ISSUE THREAD

**Issue by zachdaniel** [elixir-sqlite/ecto_sqlite3#131]
👋 sorry to bug about this in an issue tracker, but I was curious about an ETA for the next release? The PR I recently made being in a hex release is the only thing holding up the `0.1.0` release of `ash_sqlite` :).

**Comment by warmwaffles** [comment]
SOON(tm), working on it now

**Comment by zachdaniel** [comment]
Awesome, thank you :) don't rush on my account, just wanted to keep my finger on the pulse.

**Comment by warmwaffles** [comment]
I was cutting `v0.15.0` for exqlite and noticed I needed to also bump this too because your fix was in there.
