### ISSUE TITLE
Missing GH releases for v0.15.0 and v0.15.1

### ISSUE THREAD

**Issue by joeljuca** [elixir-sqlite/ecto_sqlite3#143]
Hi @warmwaffles!

I just noticed new versions on Hex for ecto_sqlite3 (`v0.15.0` and `v0.15.1`), but there's not GitHub release for these two. [The Changelog seems to be up to date](https://github.com/elixir-sqlite/ecto_sqlite3/blob/main/CHANGELOG.md), though.

I'm just pinging you here in case you forgot to create them. :)

**Comment by warmwaffles** [comment]
Yea I forgot to create them. They are up now.
