### ISSUE TITLE
Add support for placeholders

### ISSUE THREAD

**Issue by kevinlang** [elixir-sqlite/ecto_sqlite3#22]
This will likely require support from `exqlite` for named paramters: https://www.sqlite.org/c3ref/bind_blob.html

Exqlite will need to handle taking in a parameter name and finding the correct parameter index via `sqlite3_bind_parameter_index()` when it does its binding, if I am understanding correctly.

**Comment by warmwaffles** [comment]
I don't understand what placeholders are supposed to be. Other than the named `?1` within the prepared statements.

**Comment by warmwaffles** [comment]
Closing this as it's been over 3 years and to be honest, I probably wont get to it until someone asks.
