### ISSUE TITLE
I think sqlite3 supports check constraints

### ISSUE THREAD

**Issue by warmwaffles** [elixir-sqlite/ecto_sqlite3#26]
https://github.com/warmwaffles/exqlite/blob/cbd1e9c6eef74355c025158c341ccc678fe7446f/lib/ecto/adapters/exqlite/connection.ex#L510-L513

If you drill into the column definition you'll see that `CHECK` is allowed https://sqlite.org/lang_altertable.html

It doesn't support, exclude although if you can just negate the statement it might suffice.

**Comment by kevinlang** [comment]
Looked at this one. We can easily support this in a similar manner to how we support `:collate` for text-insensitive columns. The beauty of ecto/ecto_sql is that we are not limited to the list of documented options shown in [`Ecto.Migration#add/3`](https://hexdocs.pm/ecto_sql/Ecto.Migration.html#add/3)

I'll add this with some tests in the next week.

**Comment by kevinlang** [comment]
I should also clean up how we do `collate` and move that to the `column_options` func instead.
