### ISSUE TITLE
Add support for `:foreign_key_constraint` via specifying constraint name

### ISSUE THREAD

**Issue by kevinlang** [elixir-sqlite/ecto_sqlite3#28]
For all constraints, whether at column or table level, we can simply specify the constraint name ourselves. This allows us to support matching on constraint violations with changesets. 

We may be able to do this for removing the `constraint_name_hack` we use for unique constraints as well.

**Comment by warmwaffles** [comment]
Oh this is actually an interesting idea.

**Comment by kevinlang** [comment]
I was mistaken here. I assumed that since specifying the constraint name in the `CHECK` constraint lead to the name of the constraint being printed in the error message, that this behavior was consistent across all `CONSTRAINT`s.

It turns out we actually _do_ specify the `CONSTRAINT name` for our foreign key clauses, just we don't get a good message back. I'll start a thread in the SQLite3 forum asking for this as a feature request.

**Comment by warmwaffles** [comment]
I hope they look into unifying the error messages. Would be nice to have a consistent error in place so we can extract out which constraint failed easier.
