### ISSUE TITLE
Limitations and alter table

### ISSUE THREAD

**Issue by lawik** [elixir-sqlite/ecto_sqlite3#33]
Hey

Love the work you are putting into Exqlite and this adaptor.

Ran into some confusion. The docs mention "ALTER TABLE which Sqlite does not support" which runs counter to the docs: https://sqlite.org/lang_altertable.html.

Or does that language just imply that sqlite doesn't support altering constraints via alter table? I think I ran into an unsupported use of ALTER TABLE during my first tries with exqlite and just want to be certain that I will be able to add/remove fields in the future without too much pain.

**Comment by lawik** [comment]
Thanks for the clarification.

That limitation is perfectly fine by me. But currently Exqlite doesn't support alter migrations at all then? So I would need to do some table creation and copying to migrate if I'm using Exqlite for data that I can't just throw out.

Do you have any good examples of this manuever? I'm pretty likely to write up something about using SQLite with Phoenix in the near future and if I have this fairly large caveat I'd also like to offer a "this is a typical way of doing it that people have had success with".

**Comment by lawik** [comment]
Actually ended up doing some Exqlite stuff on this stream: https://youtu.be/YixXqPyASGE

**Comment by kevinlang** [comment]
AFAIK we do support most of the ALTER TABLE things that SQLite3 supports. That sentence in the doc is unclear, I meant to say that we do not support `ALTER TABLE ADD CONSTRAINT`, as SQLite3 does not support it. SQLite3's support of most ALTER TABLE things is pretty behind other databases. `ALTER TABLE DROP COLUMN` was just added a month or so ago!

I'll update the docs to make it more clear.

All the ALTER TABLE things outlined in that SQLite3 document _are_ currently supported by the `ecto_sqlite3` adapter.

**Comment by kevinlang** [comment]
I updated the documentation in a83b90115aaf1b29b651af313a22aec1752252ba

In your usage, if you encounter _anything_ that SQLite3 seems to support but the adapter does not seem to report, please open an issue. I believe we cover almost everything at this point in terms of the core SQL functionality, even if there is a way to go for custom SQLite3-only API usage

**Comment by lawik** [comment]
That's great!

I'll keep an eye out :)
