### ISSUE TITLE
Can't have a field with name "order"

### ISSUE THREAD

**Issue by lawik** [elixir-sqlite/ecto_sqlite3#38]
Hey

I think it's possible to use reserved SQL keywords as field names and such if properly escaped. Ran into a migration not running due to naming it `order`.

Figured I'd let you know.

**Comment by warmwaffles** [comment]
@lawik this has been fixed by @Jcambass  in #39 and is now released under 38efd93

**Comment by lawik** [comment]
Perfect! ✨
