### ISSUE TITLE
Add phx.gen upstream support

### ISSUE THREAD

**Issue by kevinlang** [elixir-sqlite/ecto_sqlite3#4]
To be pursued once we hit 1.0

**Comment by warmwaffles** [comment]
Is this adding it to `phx.gen`'s mix commands to allow sqlite3 to be specified?

**Comment by kevinlang** [comment]
Yep! One of the sqlite ecto2 adapters used to be included back in the Ecto 2 days from reading through old issues, but simply never got re-onboarded because there was never an ecto3 driver, so I think upstream will be amenable.

**Comment by kevinlang** [comment]
https://github.com/kevinlang/phoenix/pull/2/files

Started work here. Some additional work needed around how we generate the various config exs files

**Comment by kevinlang** [comment]
https://github.com/phoenixframework/phoenix/pull/4268

I have a PR here that is nearly ready to merge once I get the `collate` stuff published. 

After further thoughts, I don't think waiting for 1.0 is necessary per se, as long as we are _stable_, which I believe we are at this point. I don't forsee any major breaking changes in the adapter from now on, now that we have sensible defaults and full integration test coverage.

**Comment by kevinlang** [comment]
I finished up the PR and the build for it is now passing. I marked it as no longer in "draft" state.

**Comment by kevinlang** [comment]
Closing as the support was added, just waiting for merge and next release of phoenix.
