### ISSUE TITLE
Consider lowering default cache size from -64000

### ISSUE THREAD

**Issue by kevinlang** [elixir-sqlite/ecto_sqlite3#43]
In #11 we decided on having default cache size of -64000. However that means once it "warms up" to full capacity, combined with pool size of 5, we will be using 64*5=320MB of memory! I think we should lower it back to -2000.

There was a [thread](https://elixirforum.com/t/ecto-sqlite3-an-ecto3-sqlite3-adapter/38391/38) on Elixir forum discussing this.

**Comment by warmwaffles** [comment]
That sounds good with me. 64MB for my use case was a server with ~8GB of RAM and an NVMe SSD. I was also loading documents in as blobs too.

**Comment by warmwaffles** [comment]
I am going to close this for now.
