### ISSUE TITLE
[Question] upsert support

### ISSUE THREAD

**Issue by sweco-semtne** [elixir-sqlite/ecto_sqlite3#63]
Hi! 
Thank you for an excellent library. 
I'm curios if upsert is supported and specifically if the Repo.insert!(changeset, on_conflict: :nothing) should be working?

Br
Mats

**Comment by warmwaffles** [comment]
https://sqlite.org/lang_conflict.html instead of `:nothing` try `:ignore`

**Comment by warmwaffles** [comment]
@sweco-semtne I'm going to close this since it has not had any movement.
