### ISSUE TITLE
Does not dump JSON correctly with Polymorphic Embed

### ISSUE THREAD

**Issue by joshuataylor** [elixir-sqlite/ecto_sqlite3#64]
I've seen this - https://github.com/elixir-sqlite/ecto_sqlite3/issues/41

Seems that using the dumper dumps to string that can't be later read properly with SQLite, it stores it like this in a JSON field in SQLite:

```
"{\"property_type\":\"foo\",\"__type__\":\"something\"}"
```

instead of like this:
```
{"property_type": "foo", "__type__": "something"}
```

Means functions like json_extract etc won't work natively in SQLite.

[I believe it's because when dumping it's done this way:](https://github.com/mathieuprog/polymorphic_embed/blob/master/lib/polymorphic_embed.ex#L277)

```
dumper.(:map, map)
```

So with SQLite, this dumps as a string:
```
{:ok,
 "{\"foo\":\"x\",\"bar\":\"2021-12-03T07:22:16.086910Z\",\"baz\":\"xxx\",\"__type__\":\"something\"}"}
```

But with Postgres it dumps as a map:
```
{:ok,
 %{
   :something => "hello",
   "__type__" => :"Whatever"
 }}
```

Not sure if this is an ecto_sqlite3 problem or a polymorphic_embed issue.

It looks like creating normal maps works properly as JSON.

**Comment by warmwaffles** [comment]
I'll look into this a little bit more.

The json data type in sqlite3 is not actually a native type. It is stored as a string and parsed when it is loaded.

**Comment by joshuataylor** [comment]
What's strange is that if I have a "normal" map it stores correctly as JSON

**Comment by warmwaffles** [comment]
> What's strange is that if I have a "normal" map it stores correctly as JSON

Can you provide a quick example of that?

**Comment by joshuataylor** [comment]
Sorry for the delay. Here is an example repo that reproduces the issue: https://github.com/joshuataylor/sqlite_example

When doing a `mix ecto.migrate`:
```
INSERT INTO "foobar" ("baz","hello","world") VALUES (?,?,?) RETURNING "id" [42, "{\"b\":22.22,\"v\":1,\"z\":\"x\"}", "earth"]
INSERT INTO "widget" ("hello","metadata") VALUES (?,?) RETURNING "id" ["{\"b\":22.22,\"v\":1,\"z\":\"x\"}", "\"{\\\"id\\\":null,\\\"ping\\\":\\\"chrome\\\",\\\"pong\\\":100,\\\"__type__\\\":\\\"bar\\\"}\""]
```

It looks like it's a normal string for the widget type.

**Comment by warmwaffles** [comment]
Excellent, I'll take a look soon.

**Comment by warmwaffles** [comment]
I don't think I quite understand the issue.

Here's the module I used to insert a record.

```elixir
defmodule SqliteExample.Schema do
  alias SqliteExample.Repo

  alias SqliteExample.Widget
  alias SqliteExample.Bar

  def insert_widget! do
    %Widget{}
    |> Widget.changeset(%{
      hello: %{},
      metadata: %{__type__: "bar", ping: "ping 1", pong: 1}
    })
    |> Repo.insert!()
  end

  def get_widget(id) do
    Repo.get(Widget, id)
  end
end
```

Result

```
iex(5)> SqliteExample.Schema.insert_widget!
[debug] QUERY OK db=9.0ms decode=0.4ms idle=1575.0ms
INSERT INTO "widget" ("hello","metadata") VALUES (?,?) RETURNING "id" ["{}", "\"{\\\"id\\\":null,\\\"ping\\\":\\\"ping 1\\\",\\\"pong\\\":1,\\\"__type__\\\":\\\"bar\\\"}\""]
%SqliteExample.Widget{
  __meta__: #Ecto.Schema.Metadata<:loaded, "widget">,
  hello: %{},
  id: 1,
  metadata: %SqliteExample.Bar{id: nil, ping: "ping 1", pong: 1}
}
```

Fetching the result

```
iex(7)> SqliteExample.Schema.get_widget(1)
[debug] QUERY OK source="widget" db=0.0ms idle=1506.8ms
SELECT w0."id", w0."hello", w0."metadata" FROM "widget" AS w0 WHERE (w0."id" = ?) [1]
%SqliteExample.Widget{
  __meta__: #Ecto.Schema.Metadata<:loaded, "widget">,
  hello: %{},
  id: 1,
  metadata: %SqliteExample.Bar{id: nil, ping: "ping 1", pong: 1}
}
```

**Comment by joshuataylor** [comment]
```
sqlite> .open sqlite_example_dev.db
sqlite> select json_extract(hello, '$.b') from foobar;
22.22
sqlite> select json_extract(hello, '$.v') from foobar;
```

This is expected. Now as the other values are stored as a string, we can't do this.
```
sqlite> select json_extract(hello, '$.b') from foobar;
22.22
sqlite> select json_extract(hello, '$.v') from foobar;
```
select json_extract(metadata, '$.ping') from widget

sqlite> select metadata from widget;
"{\"id\":null,\"ping\":\"chrome\",\"pong\":100,\"__type__\":\"bar\"}"
```
This is stored as a string, so we can't do JSON queries on this.

**Comment by warmwaffles** [comment]
Oh this _is_ strange. Let me play with exqlite and ecto_sqlite3's serialize and deserialize stuff. I hope this doesn't break someone's stuff that exists already.

**Comment by warmwaffles** [comment]
Created a test to verify that the column was serialized appropriately. 

https://github.com/elixir-sqlite/ecto_sqlite3/commit/9c5f5a46bbacf24e6bbf4ddfac894e7de8095be7

**Comment by warmwaffles** [comment]
I'm not quite done with it yet because clearly I can reproduce it with your repository and inspect with sqlite3 on the command line.

**Comment by joshuataylor** [comment]
With postgres, putting a `IEX.pry` on  `dumper.(:map, map)` ([here](https://github.com/mathieuprog/polymorphic_embed/blob/master/lib/polymorphic_embed.ex#L277))

returns:
`{:ok, %{:id => nil, :ping => "chrome", :pong => 100, "__type__" => :bar}}`

With sqlite, it returns the string:
{:ok, "{\"id\":null,\"ping\":\"chrome\",\"pong\":100,\"__type__\":\"bar\"}"}

**Comment by joshuataylor** [comment]
I believe it's because it's double json encoded, once from a map to a string, then from a string to another string.

If a check is added to `json_encode` for checking if it's a bitstring, this fixes it.
```
  def json_encode(value) when is_bitstring(value), do: {:ok, value}
```

It would be better to check upstream in the dumpers in sqlite3.ex, but I'm unsure how to do this (the &Codec.json_encode/1 looks like magic to me).

**Comment by warmwaffles** [comment]
Let me noodle on promoting that into exqlite. I think it has merit for sure.

**Comment by warmwaffles** [comment]
In the mean time, let's put your first suggestion with the guard clause in.

**Comment by joshuataylor** [comment]
Sorry, I meant https://github.com/elixir-sqlite/ecto_sqlite3/blob/main/lib/ecto/adapters/sqlite3.ex#L383 .

I don't believe it's an exqlite issue, but an ecto_sqlite3 issue of double encoding. I made a misspoke and should have said in the other function. #:facepalm:

**Comment by warmwaffles** [comment]
Yea the dumpers are confusing for sure, but those only deal with the actual `field :foo, :map` stuff and `field :foo, array: :string`. The guard clause bit will need to live in the codecs.

**Comment by warmwaffles** [comment]
@joshuataylor released under `v0.7.5`

**Comment by joshuataylor** [comment]
Fantastic! Also with sqlite 3.38 you can now do ->> for json selectors (same as Postgres), which is great.

Can confirm this works.

**Comment by warmwaffles** [comment]
Oh that's something I wanted to add some tests for to demonstrate it working.
