### ISSUE TITLE
Immediate transaction

### ISSUE THREAD

**Issue by LostKobrakai** [elixir-sqlite/ecto_sqlite3#68]
I've a usecase for a read-then-update flow and I was considering using an immediate transaction to prevent the race condition of a concurrent transaction changing the db after the initial read, but before updates were written. I saw exqlite has some code around those, but I'm wondering if that can be exposed to ecto based transactions.

**Comment by warmwaffles** [comment]
I'm not sure how to set the mode for the transaction from within ecto, but the `db_connection` implementation supports it

https://github.com/elixir-sqlite/exqlite/blob/b45c25c6509e56530baccea97b1c1363b0892f02/lib/exqlite/connection.ex#L195-L196

**Comment by LostKobrakai** [comment]
I just noticed this just works: `Edith.Repo.transaction(…, mode: :immediate)` :)

**Comment by warmwaffles** [comment]
I didn't realize that `transaction/2` took that as an option. It isn't documented AFAIK.

**Comment by warmwaffles** [comment]
Perhaps a PR to upstream ecto would be welcome about passing the mode. I believe postgres and mysql implementations support the `mode:` directive.
