### ISSUE TITLE
Support "EXPLAIN QUERY PLAN"

### ISSUE THREAD

**Issue by LostKobrakai** [elixir-sqlite/ecto_sqlite3#76]
In sqlite `EXPLAIN QUERY PLAN …` and `EXPLAIN …` return different values. Currently only the latter is supported with `Repo.explain(:all, query)`, but I'd expect that the first one is actually the more common need, why people reach for explain. I think both options should be available (as enabled via the `opts`), but I think `EXPLAIN QUERY PLAN` should be the default, rather than just `EXPLAIN`.

**Comment by LostKobrakai** [comment]
It would also be great if aliases and parameters could be replaced in the result. I'm not sure how involved this is though.

**Comment by warmwaffles** [comment]
It's a pretty quick add https://github.com/elixir-sqlite/ecto_sqlite3/blob/edef95fb3619a4090003d5c94cd527b6073928a4/lib/ecto/adapters/sqlite3/connection.ex#L657-L659
