### ISSUE TITLE
Better handling of thundering herd connection problem

### ISSUE THREAD

**Issue by kevinlang** [elixir-sqlite/ecto_sqlite3#8]
Right now we hook into the `:configure` function we handle off to `DBConnection.child_spec` to sleep a random time between 0-50ms. But that randomness can "fail" and we can still hit a "database is locked" issue if two processes both roll the same die.

A better solution is to use the `:pool_index` option provided to us then to more evenly space out the sleeping (e.g., each connection spaced ~5ms apart). That should eliminate the "database is locked" error log for nearly every case.

There is also a TODO there around making sure we respect any `:configure` options passed in, which we will also want to address. I'm not sure if that would ever happen, though.

**Comment by warmwaffles** [comment]
Instead of doing random, would doing a modulo of the current time with how many connections there are work? Would be nice if the pool implemented a round robin style pool allocation.

**Comment by warmwaffles** [comment]
Oh we are talking about roughly the same thing.

**Comment by kevinlang** [comment]
Split out the configure wrapping thing to #10
